options {
    directory "/var/cache/bind";

    listen-on { any; }; // Слушаем на всех интерфейсах IPv4
    listen-on-v6 { none; }; // Отключаем прослушивание на IPv6

    allow-query { any; }; // Разрешаем запросы от всех источников

    recursion no; // Отключаем рекурсию, сервер работает только в режиме авторитетных ответов

    dnssec-validation auto; // Включаем автоматическую валидацию DNSSEC

    auth-nxdomain no; // Соответствие стандарту RFC1035
};

// Настройка корневой зоны
zone "." {
    type hint;
    file "/usr/share/dns/root.hints";
};

// Зона example.com (слейв для ns1)
zone "example.com" {
    type slave;
    file "/var/cache/bind/slaves/db.example.com";
    masters { 172.28.1.1; }; // IP адрес ns1
};

// Зона example.ru (слейв для ns1)
zone "example.ru" {
    type slave;
    file "/var/cache/bind/slaves/db.example.ru";
    masters { 172.28.1.1; }; // IP адрес ns1
};

// Зона example.net (мастер для ns3)
zone "example.net" {
    type master;
    file "/etc/bind/master/example.net.zone"; // Путь к файлу зоны
    allow-transfer { 172.28.3.3; }; // Разрешаем передачу зоны на ns3
    notify yes; // Уведомляем ns3 о передаче зоны
};

// Включаем ключ rndc для управления сервером
include "/etc/bind/rndc.key";

// Конфигурация для управления сервером через rndc
controls {
    inet 127.0.0.1 port 953;
    allow { 127.0.0.1; }; // Управление доступно только с localhost
    keys { "rndc-key"; }; // Ключ для авторизации
};
